server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:  admin
    url: jdbc:postgresql://localhost:5432/postgres