spring:
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: db/changelog-master.xml
    check-change-log-location: true
